apiVersion: v1
kind: Service
metadata:
  name: cashew-backend
  namespace: cashew-capital
spec:
  type: ClusterIP
  selector:
    app: cashew-backend
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
